"""added indexing to blog_id in post table

Revision ID: 82e42ca33949
Revises: cd8260a6b876
Create Date: 2026-08-05 00:27:35.369168

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '82e42ca33949'
down_revision: Union[str, Sequence[str], None] = 'cd8260a6b876'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_posts_blog_id'), 'posts', ['blog_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_posts_blog_id'), table_name='posts')
    # ### end Alembic commands ###
