"""Add private blogs

Revision ID: d04c1efddb8a
Revises: 82e42ca33949
Create Date: 2026-09-22 22:10:40.848909

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd04c1efddb8a'
down_revision: Union[str, Sequence[str], None] = '82e42ca33949'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('blogs', sa.Column('is_published', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('blogs', 'is_published')
    # ### end Alembic commands ###
