name: Build and Deploy Full Stack app

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

permissions:
  id-token: write
  contents: read

jobs:
  build-backend:
    environment:
      name: testing
    env:
      POSTGRES_HOST: ${{secrets.POSTGRES_HOST}}
      POSTGRES_PORT: ${{secrets.POSTGRES_PORT}}
      POSTGRES_PASSWORD: ${{secrets.POSTGRES_PASSWORD}}
      POSTGRES_DB: ${{secrets.POSTGRES_DB}}
      POSTGRES_USER: ${{secrets.POSTGRES_USER}}
      JWT_SECRET_KEY: ${{secrets.JWT_SECRET_KEY}}
      JWT_ALGORITHM: ${{secrets.JWT_ALGORITHM}}
      JWT_ACCESS_TOKEN_EXPIRE_MINUTES: ${{secrets.JWT_ACCESS_TOKEN_EXPIRE_MINUTES}}
      JWT_REFRESH_TOKEN_EXPIRE_DAYS: ${{secrets.JWT_REFRESH_TOKEN_EXPIRE_DAYS}}

    services:
      postgres:
        image: postgres
        env:
          POSTGRES_PASSWORD: ${{secrets.POSTGRES_PASSWORD}}
          POSTGRES_DB: ${{secrets.POSTGRES_DB}}_test
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    runs-on: ubuntu-latest
    steps:
      - name: pulling git repo
        uses: actions/checkout@v7
      - name: install python version 3.11
        uses: actions/setup-python@v7
        with:
          python-version: "3.11"
      - name: upgrade pip
        run: python -m pip install --upgrade pip
      - name: install all python backend dependencies
        run: pip install -r server/requirements.txt
      - name: test with pytest
        run: |
          pip install pytest
          pytest

  deploy:
    runs-on: ubuntu-latest
    environment: deployment
    needs: build-backend
    env:
      AWS_REGION: ${{secrets.AWS_REGION}}
      EC2_INSTANCE_ID: ${{ secrets.EC2_INSTANCE_ID }}

    steps:
      - name: Configure AWS credentials using OIDC
        uses: aws-actions/configure-aws-credentials@v6
        with:
          role-to-assume: ${{ secrets.AWS_IAM_ROLE }}
          aws-region: ${{ secrets.AWS_REGION }}
      - name: Deploy directly to EC2 using SSM
        run: |
          COMMAND_ID=$(aws ssm send-command \
            --instance-ids "$EC2_INSTANCE_ID" \
            --document-name "AWS-RunShellScript" \
            --comment "Deploy Ink application using Github Actions" \
            --parameters 'commands=[
              "set -e",
              "cd /home/blog-app/app/src",
              "git pull origin main",
              "cd client",
              "npm ci",
              "export VITE_API_URL="https://ink-app-api.duckdns.org"
              "rm -rf dist",
              "npm run build",
              "sudo mkdir -p /var/www/ink-frontend",
              "sudo rm -rf /var/www/ink-frontend/*",
              "sudo cp -r dist/. /var/www/ink-frontend/",
              "sudo chown -R www-data:www-data /var/www/ink-frontend",
              "sudo nginx -t",
              "sudo systemctl reload nginx",
              "sudo systemctl restart ink-app-api",
            ]' \
            --query "Command.CommandId" \
            --output text)

          echo "SSM command ID: $COMMAND_ID"

          aws ssm wait command-executed \
          --command-id "$COMMAND_ID" \
          --instance-id "$EC2_INSTANCE_ID"

          aws ssm get-command-invocation \
          --command-id "$COMMAND_ID" \
          --instance-id "$EC2_INSTANCE_ID"
